apiVersion: v1
kind: Pod
metadata:
  name: pvc-access
spec:
  containers:
  - name: shell
    image: registry.access.redhat.com/ubi9/ubi
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: models
      mountPath: /mnt/models
  volumes:
  - name: models
    persistentVolumeClaim:
      claimName: pvc-finetuned-models
